import { currentUser, employeeProfiles, payslips, sickReports, timeEntries, vacationRequests } from '../../lib/mock-data';
import { Notice, PageHeader, Section, StatCard, StatusBadge } from '../../components/ui/primitives';

const me = employeeProfiles[0];

export const EmployeeDashboard = () => <div className='space-y-4'><PageHeader title={`Guten Morgen, ${currentUser.name.split(' ')[0]}!`} description='Ihr Überblick für den heutigen Arbeitstag.' action={<button className='btn btn-primary' disabled>Nächste Aktion: Pause starten</button>} /><div className='grid gap-4 md:grid-cols-3'><StatCard label='Aktueller Status' value='Eingestempelt' hint='Letzte Buchung: 08:02 Uhr' /><StatCard label='Arbeitszeit heute' value='07:42 h' hint='Pause: 00:32 h' /><StatCard label='Urlaub verfügbar' value='18 Tage' hint='Geplant/Genehmigt: 4 Tage' /></div><Section title='Meine Aufgaben'><ul className='space-y-2 text-sm'><li>• Monat April bestätigen</li><li>• Neue Lohnabrechnung verfügbar</li><li>• Krankmeldung: Dokument ausstehend</li></ul></Section></div>;

export const TimeClockPage = () => <div className='space-y-4'><PageHeader title='Zeiterfassung' description='Zeitbuchungen als Platzhalter-Oberfläche.'/><Section title='Aktueller Status'><div className='flex flex-wrap items-center gap-2'><StatusBadge status='Eingestempelt' /><span className='text-sm text-slate-600'>Letzte Buchung: 08:02 Uhr</span></div><div className='mt-3 grid gap-3 sm:grid-cols-2'><button className='btn btn-primary py-3' disabled>Einstempeln</button><button className='btn btn-primary py-3' disabled>Pause starten</button><button className='btn btn-primary py-3' disabled>Pause beenden</button><button className='btn btn-primary py-3' disabled>Ausstempeln</button></div></Section><Section title='Heutiger Verlauf'><ul className='text-sm space-y-1'><li>Eingestempelt 08:02</li><li>Pause gestartet 12:03</li><li>Pause beendet 12:35</li><li>Ausstempeln 17:02</li></ul><p className='mt-2 font-medium'>Gesamt heute: 08:28 h</p></Section><Notice>Mockdaten — echte Zeiterfassung folgt später.</Notice></div>;

export const MyHoursPage = () => <div className='space-y-4'><PageHeader title='Meine Stunden' description='Monatsübersicht, Bestätigung und Korrekturhinweise.'/><div className='grid gap-4 md:grid-cols-4'>{['Offen','Zur Prüfung','Bestätigt','Nachträglich geändert'].map(s=><StatCard key={s} label={s} value='1' />)}</div><div className='grid gap-4 md:grid-cols-4'><StatCard label='Arbeitstage' value='21'/><StatCard label='Gesamtstunden' value='165:30 h'/><StatCard label='Pausenzeit' value='10:15 h'/><StatCard label='Korrekturhinweise' value='2'/></div><Section title='Einträge April 2026'><div className='overflow-x-auto'><table className='w-full min-w-[760px] text-sm'><thead><tr className='text-left text-slate-500'><th>Datum</th><th>Einstempeln</th><th>Ausstempeln</th><th>Pause</th><th>Arbeitszeit</th><th>Status</th></tr></thead><tbody>{timeEntries.filter(t=>t.employeeId==='u1').map(t=><tr key={t.id} className='border-t'><td className='py-2'>{t.date}</td><td>{t.start}</td><td>{t.end}</td><td>{t.breakMinutes} min</td><td>08:10 h</td><td><StatusBadge status={t.confirmationStatus}/></td></tr>)}</tbody></table></div><button className='btn btn-muted mt-3' disabled>Monat bestätigen</button></Section></div>;

export const PayslipsPage = () => <div className='space-y-4'><PageHeader title='Lohnabrechnungen' description='Sicherer Dokumentenbereich (Platzhalter).'/><Notice>Lohnabrechnungen werden später nur nach Anmeldung und Berechtigung abrufbar sein.</Notice><Section title='Dokumente'><div className='overflow-x-auto'><table className='w-full min-w-[700px] text-sm'><thead><tr className='text-left text-slate-500'><th>Monat</th><th>Jahr</th><th>Status</th><th>Bereitgestellt am</th><th>Aktion</th></tr></thead><tbody>{payslips.map(p=><tr key={p.id} className='border-t'><td className='py-2'>{p.month}</td><td>{p.year}</td><td><StatusBadge status={p.status}/></td><td>{p.providedAt}</td><td><button className='btn btn-muted' disabled>Herunterladen</button></td></tr>)}</tbody></table></div></Section></div>;

export const VacationPage = () => <div className='space-y-4'><PageHeader title='Urlaub' description='Kontostände und Anträge (Mockdaten).' action={<button className='btn btn-primary' disabled>Urlaub beantragen</button>} /><div className='grid gap-4 md:grid-cols-5'><StatCard label='Jahresurlaub' value={`${me.urlaubstageProJahr}`}/><StatCard label='Genommen' value='8'/><StatCard label='Geplant / Genehmigt' value='4'/><StatCard label='Anpassung' value='+0'/><StatCard label='Verfügbar' value='18'/></div><Section title='Anträge'><div className='overflow-x-auto'><table className='w-full min-w-[860px] text-sm'><thead><tr className='text-left text-slate-500'><th>Zeitraum</th><th>Tage</th><th>Status</th><th>Eingereicht am</th><th>Kommentar</th><th>Aktion</th></tr></thead><tbody>{vacationRequests.filter(v=>v.employeeId==='u1').map(v=><tr key={v.id} className='border-t'><td className='py-2'>{v.from} – {v.to}</td><td>{v.days}</td><td><StatusBadge status={v.status}/></td><td>{v.submittedAt}</td><td>{v.comment}</td><td><button className='btn btn-muted' disabled>Stornieren</button></td></tr>)}</tbody></table></div></Section><Notice tone='warning'>Feiertage und Sonderfälle werden im MVP manuell geprüft.</Notice></div>;

export const SickLeavePage = () => <div className='space-y-4'><PageHeader title='Krankmeldung' description='Datensparsam und nachvollziehbar.' action={<button className='btn btn-primary' disabled>Krankmeldung melden</button>} /><Notice tone='warning'>Keine Diagnose speichern.</Notice><Section title='Meldungen'><div className='overflow-x-auto'><table className='w-full min-w-[760px] text-sm'><thead><tr className='text-left text-slate-500'><th>Zeitraum</th><th>Status</th><th>Dokument</th><th>Gemeldet am</th></tr></thead><tbody>{sickReports.filter(s=>s.employeeId==='u1').map(s=><tr key={s.id} className='border-t'><td className='py-2'>{s.from} – {s.to}</td><td><StatusBadge status={s.status}/></td><td><StatusBadge status={s.documentStatus}/></td><td>{s.submittedAt}</td></tr>)}</tbody></table></div></Section><Notice>eAU-Integration folgt später.</Notice></div>;

export const ProfilePage = () => <div className='space-y-4'><PageHeader title='Profil' description='Persönliche Stammdaten und Arbeitsmodell.'/><div className='grid gap-4 lg:grid-cols-2'><Section title='Persönliche Daten'><dl className='space-y-1 text-sm'><dt>Name: {currentUser.name}</dt><dt>E-Mail: {currentUser.email}</dt><dt>Personalnummer: {me.personalnummer}</dt><dt>Standort: {me.standort}</dt></dl></Section><Section title='Arbeitsmodell'><dl className='space-y-1 text-sm'><dt>Beschäftigungsart: {me.beschaeftigungsart}</dt><dt>Wochenstunden: {me.wochenstunden}</dt><dt>Arbeitstage pro Woche: {me.arbeitstageProWoche}</dt></dl></Section><Section title='Urlaub'><p className='text-sm'>Urlaubstage pro Jahr: {me.urlaubstageProJahr}</p></Section><Section title='Konto & Sprache'><p className='text-sm'>Account Status: {me.accountStatus}</p><p className='text-sm'>Sprache: DE (Platzhalter)</p></Section></div></div>;
