import { ReactNode } from 'react';

const Card = ({ children, className = '' }: { children: ReactNode; className?: string }) => <div className={`card ${className}`}>{children}</div>;
const H = ({ t, d }: { t: string; d: string }) => <div className='mb-4'><h1 className='text-2xl font-semibold'>{t}</h1><p className='text-sm text-slate-600'>{d}</p></div>;
const Badge = ({ s }: { s: string }) => <span className='badge border border-slate-200 bg-slate-100 text-slate-700'>{s}</span>;

export function Placeholder({ page }: { page: string }) {
  const tableWrap = 'overflow-x-auto';
  switch (page) {
    case 'emp-dashboard': return <section><H t='Guten Morgen, Erika!' d='Ihr Überblick für heute.'/><div className='grid gap-4 md:grid-cols-2 xl:grid-cols-4'>{['Status: Eingestempelt','Heute: 07:42 h','Urlaub verfügbar: 18 Tage','Letzte Lohnabrechnung: April 2026'].map(x=><Card key={x}>{x}</Card>)}</div><div className='mt-4 grid gap-4 lg:grid-cols-3'><Card className='lg:col-span-2'><h3 className='font-medium'>Meine Aufgaben</h3><ul className='mt-2 list-disc pl-5 text-sm text-slate-700'><li>Zeiterfassung für 30.04. bestätigen</li><li>Urlaubsplanung Sommer einreichen</li><li>Profil auf Aktualität prüfen</li></ul></Card><Card><h3 className='font-medium'>Schnellzugriffe</h3><div className='mt-3 space-y-2 text-sm'><div className='rounded border p-2'>Zeiterfassung öffnen</div><div className='rounded border p-2'>Urlaub beantragen</div><div className='rounded border p-2'>Lohnabrechnung ansehen</div></div></Card></div></section>;
    case 'time-clock': return <section><H t='Zeiterfassung' d='Mockdaten — echte Zeiterfassung folgt später.'/><Card><div className='grid gap-3 sm:grid-cols-2 lg:grid-cols-4'>{['Einstempeln','Pause starten','Pause beenden','Ausstempeln'].map(b=><button key={b} className='btn btn-primary py-3'>{b}</button>)}</div><div className='mt-4 flex flex-wrap gap-2'><Badge s='Eingestempelt'/><Badge s='Pause aktiv'/><Badge s='Ausgestempelt'/></div></Card><Card className='mt-4'><h3 className='font-medium'>Heute</h3><ul className='mt-2 text-sm text-slate-700'><li>08:02 Einstempeln</li><li>12:05 Pause starten</li><li>12:34 Pause beenden</li><li>17:01 Ausstempeln</li></ul><p className='mt-3 font-medium'>Gesamt: 08:30 h</p></Card></section>;
    case 'my-hours': return <section><H t='Meine Stunden' d='Monatsübersicht und Prüffreigaben.'/><div className='grid gap-4 md:grid-cols-4'>{['Offen','Zur Prüfung','Bestätigt','Nachträglich geändert'].map(s=><Card key={s}><p className='text-sm text-slate-500'>{s}</p><p className='text-2xl font-semibold'>3</p></Card>)}</div><Card className='mt-4'><div className={tableWrap}><table className='w-full min-w-[720px] text-sm'><thead><tr className='text-left text-slate-500'><th>Datum</th><th>Einstempeln</th><th>Ausstempeln</th><th>Pause</th><th>Arbeitszeit</th><th>Status</th></tr></thead><tbody>{['28.04.2026','29.04.2026','30.04.2026'].map(d=><tr key={d} className='border-t'><td className='py-2'>{d}</td><td>08:00</td><td>16:45</td><td>00:30</td><td>08:15</td><td><Badge s='Bestätigt'/></td></tr>)}</tbody></table></div></Card></section>;
    default: return <section><H t='Bereich in Vorbereitung' d='Polierter Platzhalter für MVP.'/></section>;
  }
}

export function AdminPage({ title }: { title: string }) {
  return <section><H t={title} d='UI-Platzhalter mit Mockdaten.'/><div className='grid gap-4 md:grid-cols-2 xl:grid-cols-4'>{['Aktive Mitarbeiter','Offene Urlaubsanträge','Krankmeldungen','Fehlende Bestätigungen'].map(x=><Card key={x}><p className='text-sm text-slate-500'>{x}</p><p className='text-2xl font-semibold'>12</p></Card>)}</div><Card className='mt-4'><div className='overflow-x-auto'><table className='w-full min-w-[760px] text-sm'><thead><tr className='text-left text-slate-500'><th>Name</th><th>Status</th><th>Aktion</th><th>Zeitpunkt</th></tr></thead><tbody>{['Zeitkorrektur','Lohnabrechnung hochgeladen','Urlaub genehmigt','Sick Status changed','Export erstellt'].map((a,i)=><tr key={i} className='border-t'><td className='py-2'>Max Beispiel</td><td><Badge s='Nicht bearbeitbar'/></td><td>{a}</td><td>30.04.2026 15:10</td></tr>)}</tbody></table></div></Card></section>;
}
